# -*- coding: utf-8 -*-
"""WordCount.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZONFqTu34AhhXVEkDnOFKTD0ELlpFcF
"""

print("Guggilam Chinmayi Naga Sai Lakshmi")

import string

def count_words(text):
    # Remove punctuation and convert text to lowercase
    text = text.translate(str.maketrans("", "", string.punctuation)).lower()
    words = text.split()
    return len(words)

def get_text_from_user():
    return input("Enter the text: ")

def get_text_from_file():
    try:
        file_name = input("Enter the file name (with extension): ")
        with open(file_name, 'r') as file:
            return file.read()
    except FileNotFoundError:
        print("Error: File not found. Please try again.")
        return None

def main():
    print("Word Count Program")
    while True:
        print("\nChoose input method:")
        print("1. Enter text manually")
        print("2. Load text from a file")
        print("3. Exit")
        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            text = get_text_from_user()
        elif choice == '2':
            text = get_text_from_file()
            if text is None:
                continue  # Skip the rest of the loop if the file wasn't found
        elif choice == '3':
            print("Exiting the program. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            continue

        if not text.strip():
            print("Error: The text is empty. Please provide some content.")
            continue

        word_count = count_words(text)
        print(f"The number of words is: {word_count}")

        another = input("Do you want to count words in another text? (yes/no): ")
        if another.lower() != 'yes':
            print("Exiting the program. Goodbye!")
            break

if __name__ == "__main__":
    main()